apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-code-assistant.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "ai-code-assistant.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      nodePort: {{ .Values.service.nodePort }}
